- .env
- compose-network/network-node/data/config/bootstrap.properties
- docker-compose.yml
- Updates container images to the latest version released on the main network environment.
- Adds Apple M1/M1X support (eg: `linux/arm64`) to the container images.
Fixes #37 
Partially Fixes #28
> Container images updated to current main network release and Apple M1/M1X support

- .env
- compose-network/network-node/settings.txt
Updates node software versions and removed unused settings.
Fixes #48
> Updates the Node Software version and removes unused settings

- README.md
Update readme
Fixes #
https://github.com/hashgraph/hedera-local-node/issues/53
**Checklist**
> 00053 update readme

- .env
> Update container versions for mainnet release 0.26.2

- .github/workflows/update-config-files.yaml
> Prevent creating duplicate config change PRs

- src/cliHelper.js
Signed-off-by: nikolay <n.atanasow94@gmail.com>
Fixes #
- https://github.com/hashgraph/hedera-local-node/issues/76
**Checklist**
> Fix/Connection refused for Mirror Node GRPC

- .env
Signed-off-by: Nana-EC <nana@swirldslabs.com>
Bump Relay to v0.2.0
Fixes #102 
**Checklist**
> Bump Relay to v0.2.0

- package-lock.json
- package.json
Signed-off-by: Ivo Yankov <ivo@devlabs.bg>
Fixes #
**Checklist**
> Bump version to 1.0.3 

- package-lock.json
- package.json
- src/hederaUtils.js
Signed-off-by: nikolay <n.atanasow94@gmail.com>
Fixes #
- https://github.com/hashgraph/hedera-local-node/issues/87
**Checklist**
> Generate ed25519 accounts on start up

- package-lock.json
- package.json
Signed-off-by: Ivo Yankov <ivo@devlabs.bg>
Fixes #
**Checklist**
> bump version to 1.1.0

- README.md
- cli.js
Add option --d / --detached for starting the node in detached mode.
Fixes #139 
**Checklist**
> feat: Add option for detached mode

- cli.js
- src/cliHelper.js
Resolve a Windows speciffic issue with starting the local node, that causes it to freeze and never actually start the docker images.
Fixes #
**Checklist**
> Fix local node to work on Windows

- .gitignore
- README.md
- cli.js
- package.json
- src/cliHelper.js
- src/hederaUtils.js
Adds a `--host`option for the cli.js
Issue # 136 (Q&A)
https://github.com/hashgraph/hedera-local-node/discussions/136
> Added host option for cli.js

- .env
Updates the version numbers to match the main network. 
| Node Software | Mirror Node | JSON RPC Relay |
| --------------- | ------------ | ----------------- |
| 0.28.7                | 0.61.1            | 0.6.0                     |
Fixes #151
> Update software versions to match the current main network release

- cli.js
- compose-network/mirror-node/application.yml
- compose-network/network-node/data/config/bootstrap.properties
Optimizations to speed up rcd file export.
Also minor bugfix.
Fixes #130 
**Checklist**
> Optimize the performance through local node

- package-lock.json
- package.json
> Bump version 2.0.0

- configs/local.json
- configs/mainnet.json
- configs/previewnet.json
- configs/testnet.json
- src/utils/nodeController.js
- templates/local/.env.template
- templates/local/application.template.yml
- templates/local/bootstrap.template.properties
- Remove sidecar properties
- Remove timeout properties for all networks except local(older mirror node version doesn't have)
Fixes #
**Checklist**
> Remove sidecar properties and timeout

- package-lock.json
- package.json
- src/utils/cliOptions.js
- src/utils/nodeController.js
> Bump to version 2.0.1

- package-lock.json
- package.json
Bump local-node version to v2.1.0
Fixes #
**Checklist**
> Bump version to 2.1.0

- package-lock.json
- package.json
Signed-off-by: nikolay <n.atanasow94@gmail.com>
Fixes #
**Checklist**
> Bump version 2.1.1

- cli.js
- package-lock.json
- package.json
- Bump Hedera SDK version
- Add additional start check for network node
Fixes #191 
**Checklist**
> Fix local node occasionally fails to start

- cli.js
- package-lock.json
- package.json
- src/utils/testNode.js
Add script to test environment readiness.
Run `npm run test:readiness` to perform `account creation`, `hbar transfer` and `token create` test.
Fixes #51 
**Checklist**
> Add environment readiness test flow

- configs/local.json
- templates/local/bootstrap.template.properties
Signed-off-by: nikolay <n.atanasow94@gmail.com>
Fixes #209
**Checklist**
> Add feature flag for atomicCryptoTransfer

- .env
- docker-compose.yml
- package-lock.json
- package.json
- templates/.env.template
- templates/local/.env.template
> Official hedera explorer image

- package-lock.json
- package.json
Signed-off-by: Maksim Dimitrov <dimitrov.maksim@gmail.com>
Fixes #
**Checklist**
> Bump version to v2.2.1

- docker-compose.yml
> Can't access local hashscan explorer

- configs/local.json
> Bump the relay image version

- package-lock.json
- package.json
> Release v.2.3.0

- package-lock.json
- package.json
Bump hedera-local-node version to 2.3.2
Fixes #
**Checklist**
> Release Version 2.3.2

- package-lock.json
- package.json
Bump local-node version to v2.4.0
Fixes #
**Checklist**
> Bump local-node version to v2.4.0

- package-lock.json
- package.json
Bump Version To v.2.4.1
Fixes #
**Checklist**
> Bump Version To v.2.4.1

- package-lock.json
- package.json
> Bump Version to 2.4.2

- package-lock.json
- package.json
> Bump Version to 2.4.3

- package-lock.json
- package.json
> Release v2.4.4

- package-lock.json
- package.json
> Bump hethers version

- README.md
- cli.js
- src/utils/hederaUtils.js
Fixes #265 and #280 
**Checklist**
> Review and update readme

- package-lock.json
- package.json
- src/tui/index.js
- test/cypress/package-lock.json
- test/cypress/package.json
Swap blessed-contrib with blessed-terminal, which fixes vulnerability.
Fixes #
**Checklist**
> Remove blessed vulnerability

- package-lock.json
- package.json
- test/smoke/package-lock.json
- test/smoke/package.json
Bump package version to 2.8.0
Fixes #
**Checklist**
> Release 2.8.0

- docker/main-network-node/Dockerfile
- docker/network-node-base/Dockerfile
- docker/network-node-haveged/Dockerfile
This PR updates Dockerfile definitions to address Sonarcloud hotspots
* Modify Dockerfiles
Fixes #321 
**Checklist**
> Fix Sonarcloud hotspots

- docs/evm-optimized.md
Add docs with diagrams explaining different modes.
Fixes #287 
**Checklist**
> Add docs for different modes

- package-lock.json
- package.json
Bump version to 2.9.0
Fixes #
**Checklist**
> Release version 2.9.0

- package-lock.json
- package.json
Bump package version to 2.10.0
Fixes #
**Checklist**
> Bump package version to 2.10.0

- docker-compose.yml
This PR modifies the container dependencies in docker-compose to facilitate a more stable behavior in certain environments including CI
* Change docker compose definition
Fixes #
**Checklist**
> Optimize container startup order for better stability

- configs/local.json
- configs/mainnet.json
- configs/previewnet.json
- configs/testnet.json
> Bump mirror node explorer image

- package-lock.json
- package.json
> Bump release version

- package-lock.json
- package.json
> Bump local-node version

- package-lock.json
- package.json
- src/helpers/dockerCheck.js
- src/utils/nodeController.js
This PR adds check before starting if docker compose version is the right one.
Fixes #319 
**Checklist**
> Check Docker Compose version prior starting

- package-lock.json
- package.json
> Make semver non-dev dependency

- package-lock.json
- package.json
> Bump Local Node Version

- .eslintrc.js
- .husky/pre-commit
- package-lock.json
- package.json
- src/utils/accountService.js
This PR adds automatically formatting and cleaning code on commit.
Fixes #
**Checklist**
> Automatically formatting and cleaning code on commit

- package-lock.json
- package.json
> Bump Local-node version to 2.14

- package-lock.json
- package.json
This PR bumps the version of local-node to 2.15
Fixes #
**Checklist**
> Release Version 2.15

- README.md
- cli.js
- src/utils/cliOptions.js
- src/utils/nodeController.js
This PR adds account blocklisting feature flag, which can enable or disable the feature. It's false by deafault and can be enabled by adding `-b` or `-b=true` or `-blocklist`.
Follow up issue for resolving leftover items: https://github.com/hashgraph/hedera-local-node/issues/403
Fixes #
**Checklist**
> Add account blocklisting feature flag

- package-lock.json
- package.json
This PR bump the local-node version to 2.15.1
Fixes #
**Checklist**
> Bump version to 2.15.1

- package-lock.json
- package.json
- src/data/StateData.ts
- src/services/CLIService.ts
- src/services/DockerService.ts
- src/services/LoggerService.ts
- src/state/AccountCreationState.ts
- src/state/AttachState.ts
- src/state/StartState.ts
- src/types/CLIOptions.ts
This PR fixes the Terminal User Interface in the refactor codebase. 
Fixes #
**Checklist**
> Fix Terminal User Interface

- .gitignore
- package-lock.json
- package.json
- src/index.ts
- tsconfig.json
> Fix build and package

- src/configuration/local.json
- src/configuration/mainnet.json
- src/configuration/previewnet.json
- src/configuration/testnet.json
> Bump Network images

- src/controller/StateController.ts
- src/state/InitState.ts
- src/state/RecoveryState.ts
- src/state/StartState.ts
- src/types/EventType.ts
This PR adds recovery state. This state has only 2 paths for now and one is a fallback if getting the docker containers up does not work from the first time.
Fixes #
**Checklist**
> Add recovery state

- test/cypress/package-lock.json
- test/cypress/package.json
- test/smoke/package-lock.json
Bumps to latest packages to resolve dependabot all at once.
Fixes #
**Checklist**
> Bump Packages

- package-lock.json
- package.json
> fix: correct the package name

- package-lock.json
- package.json
- src/state/AccountCreationState.ts
This PR rearrange the account creation for ECDSA and ED25519 accounts to fix issue with wrong private keys.
Fixes #459 
**Checklist**
> fix: wrong ecdsa and ed25519 account generation

- src/services/CLIService.ts
This PR fixes starting the generate-accounts option and debug option in attached mode.
Fixes #460 
**Checklist**
> fix: generate account options starting in attached mode

- src/state/AccountCreationState.ts
This PR fixes the typos from the previous PR releated to the blocklisting improvment feature
Fixes #
**Checklist**
> chore: Fix typos from previous pull request

- package-lock.json
- package.json
- src/configuration/local.json
- src/configuration/mainnet.json
- src/configuration/previewnet.json
- src/configuration/testnet.json
This PR aims to bump the network images to the latest, as well as local-node network version to prepare it for release
Fixes #
**Checklist**
> chore: bump network images and version

- package-lock.json
- package.json
This PR aims to bump the local-node network version to prepare it for release
Fixes #
**Checklist**
> Bump images and versions

- package-lock.json
- package.json
- src/constants.ts
- src/services/DockerService.ts
- src/state/InitState.ts
This PR adds a check on startup for used ports. It particularly checks for ports that are essential for the startup of the local-node.
Fixes #435 
**Checklist**
> feat: adds check for used ports

- docker-compose.multinode.yml
- src/state/InitState.ts
- src/state/StartState.ts
This PR adds support for multinode after the refactor. 
* Services healthcheck
* Supports service when one of the nodes is down
* Loads all the yml files in the correct order
Fixes #436 
**Checklist**
> fix: Fixes multinode mode

- README.md
- docs/multinode-mode.md
This pr updates the README with info on `--multinode` mode and creates a new document describing the mode in depth.
Fixes #317 
**Checklist**
> docs: add multinode mode docs

- test/unit/controller/StateController.spec.ts
- test/unit/states/AccountCreationState.spec.ts
This PR adds unit tests for the AccountCreationState.
Fixes #502
> feat: Add unit tests for AccountCreationState

- test/unit/states/CleanUpState.spec.ts
This PR adds a test file for the CleanUpState class
Fixes #511
> feat: Adds unit tests for CleanUpState

- package.json
- src/constants.ts
- src/state/StopState.ts
- test/unit/states/StopState.spec.ts
- test/unit/testBed.ts
Create unit test for StopState
https://github.com/hashgraph/hedera-local-node/issues/507
> feat: Create unit test for StopState #507

- src/constants.ts
- src/services/DockerService.ts
- src/state/StartState.ts
- src/state/StopState.ts
- test/unit/states/StopState.spec.ts
- test/unit/states/startState.spec.ts
- test/unit/testBed.ts
Create unit test for StartState
[#510](https://github.com/hashgraph/hedera-local-node/issues/510)
> feat: Create unit test for StartState #510

- src/constants.ts
- src/services/DockerService.ts
- src/state/RecoveryState.ts
- test/unit/states/StopState.spec.ts
- test/unit/states/recoveryState.spec.ts
- test/unit/states/startState.spec.ts
- test/unit/testBed.ts
Create unit test for RecoveryState
[#513](https://github.com/hashgraph/hedera-local-node/issues/513)
> feat: Create unit test for RecoveryState #513

- .gitignore
- package-lock.json
- package.json
This PR adds coverage to unit tests
#495 
**Checklist**
> chore: add coverage to unit tests

- compose-network/mirror-node/init.sh
- src/configuration/local.json
- src/configuration/mainnet.json
- src/configuration/previewnet.json
- src/configuration/testnet.json
This PR fixes mirror-node init scripts, as well as bumps network nodes to latest versions
Fixes #
**Checklist**
> fix: mirror-node init script

- src/constants.ts
- src/services/DockerService.ts
- src/state/NetworkPrepState.ts
- test/unit/states/networkPrepState.spec.ts
- test/unit/states/startState.spec.ts
- test/unit/testBed.ts
Create unit test for NetworkPrepState
[#515](https://github.com/hashgraph/hedera-local-node/issues/515)
> feat: Create unit test for NetworkPrepState #515

- package-lock.json
- package.json
Update local node version to 2.18.0
Fixes #
**Checklist**
> feat: update version to 2.18.0

- src/constants.ts
- src/data/ConfigurationData.ts
- src/state/InitState.ts
- test/unit/states/InitState.spec.ts
Create unit test for InitState
[#521](https://github.com/hashgraph/hedera-local-node/issues/521)
> feat: Create unit test for InitState #521

- docs/ubuntu-setup.md
Add documentation for setting up Ubuntu system for the Hedera Local Node.
Fixes https://github.com/hashgraph/hedera-local-node/issues/266
**Checklist**
> docs: Add Ubuntu docs

- src/constants.ts
- src/state/DebugState.ts
- test/unit/states/DebugState.spec.ts
This PR adds unit tests for the DebugState class
Fixes #524
> feat: Adds debug state unit tests

- src/state/AttachState.ts
- test/unit/states/AttachState.spec.ts
This PR adds unit tests for the AttachState
Fixes #519
> feat: Adds unit tests for attach state

- .github/workflows/flow-pr-title-check.yaml
Add *Title* in the workflow name that checks titles of PRs
Fixes #530
**Checklist**
> chore: Add *Title* in the workflow name that checks titles of PRs

- package-lock.json
- package.json
- src/configuration/local.json
- src/configuration/mainnet.json
- src/configuration/previewnet.json
- src/configuration/testnet.json
> chore: bump packages

- package.json
- src/constants.ts
- test/unit/controller/StateController.spec.ts
- test/unit/states/AccountCreationState.spec.ts
- test/unit/states/CleanUpState.spec.ts
- test/unit/states/DebugState.spec.ts
- test/unit/testBed.ts
> fix: 536 fix failing unit tests

- .github/workflows/flow-pull-request-checks.yaml
- .gitignore
- package.json
Add Unit tests and coverage report that is uploaded to Codecov
Fixes #495
**Checklist**
> chore: Add unit tests and coverage report

- .env
- package-lock.json
- package.json
- src/configuration/local.json
- src/configuration/mainnet.json
- src/configuration/previewnet.json
- src/configuration/testnet.json
This PR updates to latest images and updates release to 2.19.1
Fixes #
**Checklist**
> feat: update release version and configuration

- .devcontainer/devcontainer.json
- .gitpod.yml
- docs/codespacs-setup.md
- docs/gitpod-setup.md
Adding configuration files for  Gitpod and Codespaces integration and related doc 
Fixes #400 
**Checklist**
> chore: Add configuration files for Gitpod and Codespaces integration

- .github/workflows/publish-npm-package.yaml
Adding Github Action for automatic publish of npm packeges to npmjs 
Fixes #407
**Checklist**
> chore: Add Github Action for automatic publish of npm packages

- package-lock.json
- package.json
- src/configuration/local.json
- src/configuration/mainnet.json
- src/configuration/previewnet.json
- src/configuration/testnet.json
This PR updates the network configuration to latest, as well as bumps local node version to 2.20.0
Fixes #
**Checklist**
> chore: update network configuration

- .github/workflows/publish-npm-package.yaml
Fixing typo
Fixes #407 
**Checklist**
> chore: Fix typo

- .github/workflows/flow-pr-title-check.yaml
> chore: update PR check workflow

- package-lock.json
- package.json
- src/configuration/local.json
- src/configuration/mainnet.json
- src/configuration/previewnet.json
- src/configuration/testnet.json
- test/smoke/package-lock.json
- test/smoke/package.json
This PR updates dependency packages, network configuration and local-node version to 2.21.0
Fixes #
**Checklist**
> chore: update local node configuration

- src/services/DockerService.ts
> fix: Docker resource check warning should not cause exit

- docs/codespaces-setup.md
- renamed file (spelling)
- proofreading edits
Fixes #
- nil
- nil
**Checklist**
> docs: minor - proofreading

- docs/codespaces-setup.md
Unifying the Codespaces docs with Gitpod
**Checklist**
> docs: unify codespaces docs with the gitpod one

- .env
- compose-network/mirror-node/init.sh
- src/configuration/local.json
- src/configuration/mainnet.json
- src/configuration/previewnet.json
- src/configuration/testnet.json
This PR updates all network configurations to their latest.
Fixes #587 
**Checklist**
> chore: update network images

- package-lock.json
- package.json
This PR bumps the local-node to the next minor version.
Fixes #
**Checklist**
> chore:bump local-node version

- package-lock.json
- package.json
> chore: bump local-node version

- src/configuration/types/ITokenProps.ts
- src/utils/TokenUtils.ts
> chore: fix typescript warnings

- .env
- package-lock.json
- package.json
- src/configuration/local.json
Bump relay's and service's images
Fixes #
**Checklist**
> feat: bump versions

- package-lock.json
- package.json
> chore: bump release version to 2.25.2

- docs/custom-sub-system-builds.md
How to build custom images of components
Fixes #585
**Checklist**
> docs: add how to build custom images readme

- package-lock.json
- package.json
- src/configuration/local.json
- src/configuration/mainnet.json
- src/configuration/previewnet.json
- src/configuration/testnet.json
- src/constants.ts
- src/controller/StateController.ts
- src/services/DockerService.ts
- src/services/LoggerService.ts
- src/state/AccountCreationState.ts
- src/state/CleanUpState.ts
- src/state/DebugState.ts
- src/state/InitState.ts
- src/state/ResourceCreationState.ts
- test/unit/states/AccountCreationState.spec.ts
- test/unit/states/CleanUpState.spec.ts
- test/unit/states/DebugState.spec.ts
- test/unit/states/InitState.spec.ts
This PR improves formatting and adds some colors to the logger, so errors can be easily spotted.
Also bumps network images and release version
Fixes #637 
New look:
**Checklist**
> feat: beatify logger

- .github/workflows/flow-pull-request-checks.yaml
Updates nick-fields/retry to use step-security maintained retry action.
Fixes #654
> ci: Updated nick-fields/retry v3.2.0 with step-security/retry v3.0.0

- docker-compose.yml
- docs/custom-sub-system-configs.md
Add documentation how to specify mirror node image version for each container
Fixes #588
**Checklist**
> chore: Add documentation how to specify mirror node image version

- package-lock.json
- package.json
`package.json` and `package-lock.json` didn't included  semantic release. Commands used to add them was:
```
npm install --save-dev semantic-release
npm install @semantic-release/git -D
npm install @semantic-release/changelog -D
```
**Checklist**
> ci: update package.json and package-lock.json for semantic-release

- src/configuration/local.json
This PR adds `entities.unlimitedAutoAssociationsEnabled` flag as `true`. 
Fixes #
**Checklist**
> chore: add unlimited auto associations flag

- .env
- .github/workflows/flow-pull-request-checks.yaml
- compose-network/mirror-node/application.yml
- compose-network/mirror-node/init.sh
- package-lock.json
- package.json
- src/configuration/local.json
This PR fixes latest mirror node version, by adding updated init.sh script for database, as well as bumping to latest network images.
Fixes #707 
**Checklist**
> fix: latest mirror node version

- .env
- .github/workflows/flow-pull-request-checks.yaml
- docker-compose.yml
- package-lock.json
- package.json
- src/configuration/local.json
This PR fixes issue with latest docker rate limiting, by changing the image path to a github registry. Also bumps the package version, in order to relase.
Fixes #
**Checklist**
> fix: rate limiting

- .github/CODEOWNERS
- .github/workflows/flow-pull-request-checks.yaml
- codecov.yml
Updated repo with codecov.yml configuration, updated workflows to use the codecov token, updated CODEOWNERS to reflect current standard
Fixes #719
> chore: Configure codecov and update CODEOWNERS

- package-lock.json
- package.json
> chore: bump version to 2.29.2

- package-lock.json
- package.json
- src/state/InitState.ts
> fix: local node fails to start with custom `--network-tag`

- .env
- package-lock.json
- package.json
- src/configuration/local.json
> chore: bump image tags of network, relay and mirror

- .env
- package-lock.json
- package.json
- src/configuration/local.json
> chore: Bump mirror image tag from 0.113.2 to 0.114.1

- compose-network/grafana/dashboards/json-rpc-relay/hedera-json-rpc-relay-http-server.json
- compose-network/grafana/dashboards/json-rpc-relay/webSocketServer.json
Updated relay's dashboards
Fixes #831 
This PR copies the JSON RPC Relay's dashboards from its repository.
> feat: JSON RPC Relay dashboards.

- src/configuration/local.json
> feat: bump versions of CN, MN and relay

- package-lock.json
- package.json
> feat: bump version to 2.32.0

- package-lock.json
- package.json
- src/configuration/local.json
> feat: bump to 2.32.1

- .env
- package-lock.json
- package.json
- src/configuration/local.json
> feat: bump to 2.32.2

- package-lock.json
- package.json
> feat: bump version

- .github/workflows/flow-pull-request-checks.yaml
Downgrade codecov-action to a stable version
Fixes #873 
**Checklist**
> ci: Downgrade codecov-action to a stable version

- package-lock.json
- package.json
- src/configuration/local.json
> chore: set default value of `scheduling.longTermEnabled` to `true`

- .github/CODEOWNERS
Renames devops-ci to platform-ci
Fixes #906
> chore: Update team name from devops-ci to platform-ci

- src/configuration/local.json
This PR adds support for frictionless airdrop by modifying the local.json config file by updating the services version + enabling the feature flags as specified in [the design doc](https://github.com/hashgraph/hedera-services/blob/v0.56.1/hedera-node/docs/design/services/smart-contract-service/frictionless-airdrops-system-contracts.md)
Fixes #890 
**Checklist**
> feat: adds support for frictionless airdrops

- .github/workflows/flow-pr-title-check.yaml
> ci: Update flow-pr-title-check.yaml

- compose-network/mirror-node/application.yml
- src/configuration/local.json
Bump the MN image.
Fixes: #949
> chore: bump MN image to 0.124.0-rc1

- src/configuration/local.json
Bump the services version to `0.61.0`.
Fixes #994 
**Checklist**
> feat: bump services version to `0.61.0`

- package-lock.json
- package.json
Bump local node package to v2.35
Fixes #
**Checklist**
> chore: Bump local node package to v2.35

- src/constants.ts
fix type that shows in the console: 
```
[Hedera-Local-Node] INFO (AccountCreationState) [✔︎] Accounts created succefully!
```
Fixes #1013 
**Checklist**
> fix: update constants.ts

- package-lock.json
- package.json
This PR aims to hold the current SDK version, as later ones have bug. And bump a patch version so that the SDK team can use it to fix the problem on their side.
Fixes #1064 
**Checklist**
> chore: hold the sdk version

- package-lock.json
- package.json
- test/unit/states/AccountCreationState.spec.ts
- test/unit/utils/AccountUtils.spec.ts
This PR aims to bump sdk version to 2.64.5 and local-node version to 2.36.2
Fixes #
**Checklist**
> chore: release version 2.36.2

- package-lock.json
- package.json
- src/configuration/local.json
This PR bumps the component version used
Fixes #
**Checklist**
> chore: bump images and version
