.github/workflows/update-config-files.yaml

- Adds a Github Workflow to automatically open a PR when there are configuration changes found in the `hashgraph/hedera-services` repository configuration files.
- Uses the `previewnet` configuration folder in the source repository.
- Automatically tags the following people as reviewers on the created PR:
- @Neeharika-Sompalli 
- @beeradb 
- @nathanklick  
- @tannerjfco 
- @steven-sheehy 
- Automatically assigns the PR to the following people:
- @swirlds-automation   
- Uses the `diff` command to check for file changes.
- Automatically runs daily at midnight.
- Will create a new PR daily until changes are merged. 
- Might want to change this behavior or increase time between runs. 
Closes #2
- Please ensure that this includes …

Add Github Action to synchronize the standard configuration files

---

.env
README.md
docker-compose.yml

Add env variables for various memory limits

---

.env

Signed-off-by: Nathan Klick <nathan@swirldslabs.com>
Update mirror node version to `0.58.0` to match mainnet mirror node version.
Fixes #98

Update mirror node version to 0.58 to match mainnet mirror node version

---

.github/workflows/update-config-files.yaml

Signed-off-by: lukelee-sl <luke.lee@swirldslabs.com>
Update GitHub workflow to use the configuration for previewnet when setting up local node.  
https://github.com/hashgraph/hedera-services/pull/4061

Update configuration file to use previewnet's configuration

---

src/helpers/connectionCheck.js
src/utils/nodeController.js

This PR modifies check connection timeout and the stop action in order to improve performance on startup and shutdown
* Change timeout
* Change docker command
Addresses #162 
Startup on a 2020 Intel MacBook Pro before took on average 1:58 m, after on average 1:06 m
Stop on the same machine before took on average 31 s, after on average 7 s
**Checklist**

Performance updates

---

docker-compose.evm.yml

This PR adds an EVM layer for the docker compose definitions. The mirror node code configuration changes below will need to be incorporated into a template via a separate issue/PR. 
To utilize the EVM overlay, docker compose should be launched with these additional arguments: 
`-f docker-compose.yml -f docker-compose.evm.yml`
**Example:**
```
docker-compose -f docker-compose.yml -f docker-compose.evm.yml up -d
```
```yaml
hedera:
importer:
..............
downloader:
........
sources:
- type: LOCAL
dataPath: file:///node/
............
```
```
diff --git forkSrcPrefix/compose-network/mirror-node/application.yml forkDstPrefix/compose-network/mirror-node/application.yml
index 66152ae92758b1450c82e2ec31dded7791861b4c..06b0f4069255136ec6962fc65cedb4481e4c6170 100644
--- …
```

feat: add a docker compose overlay to disable minio/mirror.py for EVM testing

---

README.md
cli.js
src/utils/cliOptions.js
src/utils/nodeController.js

This PR changes configuration to enable starting of turbo mode to default.
Also adds full mode for starting a production-like local-node. Can be started with `--full`
Fixes #303 
**Checklist**

Set Turbo mode to be default

---

cli.js
src/utils/nodeController.js

Thus PR modifies `NodeController.js` and `cli.js` in order to `host` option can affect the `VUE_APP_LOCAL_MIRROR_NODE_URL` env variable.
So when starting hedera-local-node with option `--host`, hedera-explorer can fetch data from the actual host that the operator sets in arguments.
Fixes #333 
Explorer fetch from the host set with `--host` option with this PR.
**Checklist**

Make host option affect explorer mirror node url

---

cli.js
src/utils/accountService.js

This PR fixes:
1. `hedera generate-accounts` doesn't terminate: displays accounts then just hangs until you `^C` manually.
2. When you do `hedera generate-accounts` it shows the 3 sections for each type of account keys but no longer shows the heading for each section telling you which section is which.
Fixes #
**Checklist**

Fix Account Generation

---

cli.js
src/utils/cliOptions.js
src/utils/nodeController.js

This PR adds two new cli options
`--usercompose` with a default value of `true`, which enables/disables support for user Compose definitions
`--composedir` with a default value of "./overrides" which defines the directory containing the desired user Compose definitions
When the option is enabled it loads all of the files in the specified directory in alphabetical order as additional Compose definitions allowing the user to modify the default local node setup.
* Add cli options
Fixes #330 
Here's an example of a custom Compose definition, that disables prometheus and grafana it can be put in a file with ".yml" extension in a `overrides` directory at the root of the project to test
```yaml
services:
grafana:
profiles:
- disabled …
```

Add support for user Compose definitions

---

src/utils/nodeController.js

This PR fixes a bug which prevents the proper parsing of cli arguments for the `start` and `restart` commands.
Fixes #
**Checklist**

Fix cli argument parsing

---

cli.js
src/helpers/dockerCheck.js
src/utils/constants.js

In some cases we check for the images version, before they are started, therefore this results in an error. This PR fixes this by setting the version to Unknown and afterwards updating it to the actual when the containers are started.
Also fixes issue when starting normal mode (not detached)
Fixes #347 
**Checklist**

Fix Docker Check error

---

package-lock.json
package.json

This PR bumps hedera-local-node version to 2.13
Fixes #
**Checklist**

Bump Local Node Version

---

README.md
package-lock.json
package.json
src/utils/accountService.js
src/utils/hederaUtils.js

This PR removes the usage of hethers.js from local-node, because this tool is deprecated now.
Also bumps all other packages to the latest versions.
Fixes #390 
**Checklist**

Remove hethers from local-node

---

docker-compose.yml

This PR aims to fix the mirror node web3 chainID to 298, which is the same as the consensus node. It was previously set to 296.
Fixes #
**Checklist**

fix: Mirror Node Web3 ChainID configuration

---

.env
.github/workflows/flow-pull-request-checks.yaml
README.md
package-lock.json
package.json
src/configuration/local.json
src/configuration/mainnet.json
src/configuration/previewnet.json
src/configuration/testnet.json

This PR aims to bump the network images to the latest, as well as local-node network version to prepare it for release
Fixes #
**Checklist**

chore: bump network images and local node version

---

src/controller/StateController.ts

This PR updates the StateController to exit if unable to transition to next state.
Fixes #450 
**Checklist**

fix: exit when unable to transition to next state

---

package.json

This PR adds an automatic build to the `npm publish` command to prevent accidental publishing of non-functioning releases to the package registry.
Fixes #470 
**Checklist**

fix: build before publishing to npm

---

src/state/AccountCreationState.ts

Default startup generated accounts ids are off, so trying to use them will result in INVALID_SIGNATURE. The expected first account ID is 0.0.1003 while the actual one is 0.0.1002 and the rest are off by 1 as well.
Fixes #
[Wrong startup account ids#474](https://github.com/hashgraph/hedera-local-node/issues/474)

fix: Wrong startup account ids #474

---

.env
README.md
src/Errors/LocalNodeErrors.ts
src/configuration/originalNodeConfiguration.json
src/constants.ts
src/data/StateData.ts
src/services/CLIService.ts
src/services/record-parser/src/Parser.java
src/state/CleanUpState.ts
src/state/DebugState.ts
src/state/InitState.ts
src/state/StartState.ts
src/utils/config.ts

run hedera debug with any valid timestmp returns the record file for that timestamp
[Fix debug mode and add documentation#269](https://github.com/hashgraph/hedera-local-node/issues/269)

feat: Adding debug mode to local node.

---

src/controller/StateController.ts
src/state/InitState.ts
src/types/EventType.ts

This PR adds `UnresolvableError` type, when something like docker is not running or is wrong version occurred.
Fixes #486 
**Checklist**

feat: add new error type and exit when needed

---

src/constants.ts
src/services/CLIService.ts
src/services/LoggerService.ts
src/types/VerboseLevel.ts

Enhance LoggerService to support an arbitrary number of verbosity levels, each having a corresponding number.
https://github.com/hashgraph/hedera-local-node/issues/497

feat: Enhance Logger Service #497

---

src/services/DockerService.ts

Trying to run local-node results in error in `docker system info` command on old versions.
Changing the format pattern resolves this issue
Running local-node occasionally fails on InitState
[#503](https://github.com/hashgraph/hedera-local-node/issues/503)

fix: Running local-node occasionally fails on InitState

---

README.md
src/services/CLIService.ts
src/state/InitState.ts
src/types/CLIOptions.ts

This PR adds 3 new options for selecting custom images for network, mirror-node and/or relay. This will allow for easier testing with different tags in CI.
Fixes #525 
**Checklist**

feat: add options for custom tags

---

src/state/AttachState.ts
test/unit/states/AttachState.spec.ts

This PR changes the onStart method in the AttachState class.
So far we had a while loop in the onStart, which was updating the statusBoard. This made testing slow and not efficient.
The while was moved to a separate function, which can be stubbed, therefore supporting better testing
Fixes #538 
**Checklist**

fix: Moves while loop to a function and stub it in the unit tests for AttаchState

---

src/configuration/local.json
src/configuration/mainnet.json
src/configuration/previewnet.json
src/configuration/testnet.json

Set network node version to `0.47.0-alpha.3` to include HIP-844 changes
Fixes #2086 in the Hedera JSON RPC Relay

fix: Updated all configurations 

---

package-lock.json
package.json
src/configuration/local.json
src/configuration/mainnet.json
src/configuration/previewnet.json
src/configuration/testnet.json

This PR aims to update the network images and bump local-node version to 2.22.0
Fixes #
**Checklist**

chore: update network images

---

README.md

This PR modifies: 
- The README to include additional `docker.socket` configuration step to ensure users have the `docker.socket` file in the right location.
- The `CLI Tool` hyperlink.
Fixes #537 and docs issue [#593](https://github.com/hashgraph/hedera-docs/issues/593)
**Checklist**

fix: include additional docker.socket configuration step

---

.env
package-lock.json
package.json
src/configuration/local.json
src/configuration/mainnet.json
src/configuration/previewnet.json
src/configuration/testnet.json

- Bumps the versions for services, mirror node and relay images for all network configurations.
- Bumps the package version number
Fixes #
**Checklist**

chore: Bump network node version to 0.49.7

---

compose-network/mirror-node/application.yml
src/services/CLIService.ts
src/state/InitState.ts
src/types/CLIOptions.ts
test/unit/states/InitState.spec.ts

This PR:
- adds a new CLI flag `--persistTransactionBytes` which will set these two properties to `true` for the mirror-node:
- `hedera.mirror.importer.parser.record.entity.persist.transactionBytes`
- `hedera.mirror.importer.parser.record.entity.persist.transactionRecordBytes`
Fixes #619 
**Checklist**

feat: Add CLI option for persistTransactionBytes

---

.github/workflows/flow-pr-title-check.yaml

version
Replaces aslafy-z/conventional-pr-title-action with the step-security maintained version
Fixes #629

ci: Update Conventional PR title check

---

package-lock.json
package.json
src/configuration/local.json
src/configuration/mainnet.json
src/configuration/previewnet.json
src/configuration/testnet.json
test/smoke/package-lock.json
test/smoke/package.json

This PRs forces usage of stable sdk version to avoid local-node freeze.
Bumps all network configurations and add feature flag to allow HIP906 feature testing.
Fixes #640 
**Checklist**

feat: fix sdk dependency

---

.env
compose-network/mirror-node/application.yml
docker-compose.yml
docs/custom-sub-system-configs.md
test/unit/states/InitState.spec.ts

**Problem**
As part of HIP-801, we need to change the mirror-node properties of the web3 module to enable the endpoint for the opcode logger which is disabled by default.
**Solution**
- We need to set the hedera.mirror.web3.opcode.tracer.enabled=true in the application.yml file with custom properties for the mirror-node.
- Change the docker configurations to override these values in the web3 module of mirror-node from the application.yml file
- Add documentation for the overridden properties of the web3 module in the local-node

feat: expose opcodes endpoint by default

---

.env
package-lock.json
package.json
src/configuration/local.json

This PR bumps all network tag to their latest versions, as well as the release tag to 2.27.1
Fixes #
**Checklist**

chore: bump network images and release tag

---

package-lock.json
package.json

Updating `package.json` and `package-lock.json` by running `npm i -D conventional-changelog-conventionalcommits`
This will allow commit-analyzer to use `conventional commits`
Fixes #
**Checklist**

ci: update package.json and package-lock.json for semantic-release

---

src/services/ConnectionService.ts
src/services/DockerService.ts
src/state/StartState.ts
src/utils/debounce.ts
test/unit/states/startState.spec.ts

- Adds the output of the externally executed commands in DockerService to the `debug` level of logs.
- Reduces the repeated error logs when waiting for a service to start up.
Fixes #412 
**Checklist**

chore: Improve log verbosity

---

.env
package-lock.json
package.json
src/configuration/local.json
src/state/InitState.ts
test/cypress/package-lock.json
test/cypress/package.json

This PR fixes an issue where local-node throws an error on startup, if you try to load images using tag command. Problem comes from the recently changed docker hub policy and deployment of havaged images to the registry. 
Because this images is not actually used, we removed the ability to change the default value using the CLI.
Also bumped the images and local-node version
Fixes #722 
**Checklist**

fix: local node not starting with tag command

---

src/constants.ts
src/services/LoggerService.ts
src/state/AccountCreationState.ts
src/utils/RetryUtils.ts
test/unit/states/AccountCreationState.spec.ts
test/unit/utils/RetryUtils.spec.ts

If the AccountCreationState begins, but the SDK is not yet connected to a healthy node, the local node would throw this error when starting up. We need to implement some sort of retry mechanism in case this issue happens.
This PR implements a retry mechanism to handle the scenario where the SDK is not connected to a healthy node at the start of the `AccountCreationState`. The retry mechanism will attempt to reconnect to a healthy node a specified number of times before failing.
**Changes:**
1. **Retry Mechanism:**
- Added a new class `RetryUtils.ts` with a `retryTask` function to handle retry logic.
- Configured the retry mechanism to execute the given task a specified number of times with a delay between attempts.
2. **Integration with `AccountCreationState`:**
- …

fix: Intermittent failure on start of `AccountCreationState`

---

.github/workflows/flow-pr-title-check.yaml
.github/workflows/flow-pull-request-checks.yaml
.github/workflows/flow-semantic-release.yml
.github/workflows/publish-npm-package.yaml

This pull request changes the following:
- Updates the CI workflows `runs-on` labels to use the new Latitude.sh based runners.
- Closes #755

ci: update workflows to use latitude.sh based runners

---

.env
package-lock.json
package.json
src/configuration/local.json

This PR bumps:
- network-tag to `0.54.0-alpha.2`
- mirror-tag to `0.112.1`
Fixes #
**Checklist**

chore: bump tags of network node and mirror node

---

.github/dependabot.yml
.github/workflows/flow-pr-title-check.yaml
.github/workflows/flow-pull-request-checks.yaml
.github/workflows/flow-semantic-release.yml
.github/workflows/publish-npm-package.yaml

Updates per Q3 audit findings
Related to #704 
**Checklist**

ci: Update per Q3 audit findings

---

README.md
package-lock.json
package.json
src/services/CLIService.ts
src/services/LoggerService.ts
src/state/AttachState.ts
src/state/StartState.ts
src/types/CLIOptions.ts
test/unit/states/AttachState.spec.ts
test/unit/states/InitState.spec.ts
test/unit/states/startState.spec.ts

Running the hedera start command show the UI in the command line temporarily and then fails with:
```
─Consensus Node Log─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│[Hedera-Local-Node] INFO (RecoveryState) ⏳ Starting Recovery State...                                                                                                                                                                                                      │
│[Hedera-Local-Node] INFO (RecoveryState) ⏳ Trying to startup again... …
```

feat: deprecate sunrise tui

---

README.md
src/constants.ts
src/services/DockerService.ts
src/state/StartState.ts
src/state/StopState.ts
test/unit/states/StopState.spec.ts

Currently, if docker images are not already pulled, the local node hangs up on :point_down:, and the user has no idea what's happening.
```
[Hedera-Local-Node] INFO (StartState) ⏳ Starting Hedera Local Node...
```
**Solution**:
Add a start-up info logger if the needed images haven't been pulled yet.
```
[Hedera-Local-Node] INFO (StartState) ⏳ Starting Hedera Local Node...
[Hedera-Local-Node] INFO (DockerService) ⏳ Pulling docker images...
```
Fixes #849
**Checklist**

feat: add docker images start-up logger

---

src/state/InitState.ts
test/unit/states/InitState.spec.ts

Currently, the user is not warned if their node/npm version is outdated and doesn't meet the minimum requirements.
**Solution**:
Add a start-up check for the node/npm version.
Fixes #863 
**Checklist**

feat:  add a start-up check for minimum node and npm versions

---

compose-network/mirror-node/application.yml
docker-compose.yml

This PR aims to add the new mirror node java rest module as a docker container, with the following changes:
- Setups up the docker-compose file to include this new container.
- Setup application.yml to include the needed variables for the rest-java module.
Fixes #790 
**Checklist**

feat: Add Hedera Mirror Node Rest Java container

---

README.md

Add FAQ section in the [README.md](https://github.com/hashgraph/hedera-local-node/blob/main/README.md) for users to reference when a problem occurs.
Fixes #438 
**Checklist**

feat: add FAQ section

---

.env
docker-compose.yml
src/state/InitState.ts

Apparently, there's a bug when running this JRE version with hosts running M4 Sequoia Mac OS. See [here](https://x.com/starbuxman/status/1869887463923298748), [here](https://github.com/corretto/corretto-23/pull/10) and [here](https://medium.com/@luketn/java-on-docker-sigill-exception-on-mac-os-sequoia-15-2-9311e4775442)
**Solution**:
Set default value for `"-XX:UseSVE=0"`

feat: pass java tool options

---

src/services/DockerService.ts

For some macOS users the cloned repo directory might differ from the default one that's used from the local node `/Users/<user>/Library/Application Support/hedera-local`.
**Solution**:
Edit the error message.

feat: edit error message for MacOS Docker's File Sharing error

---

src/services/DockerService.ts

The local node does not seem to start with a custom web3 image for the mirror web3 module.
Fixes: #945

feat: use a locally built images in the local node

---

.github/workflows/flow-pull-request-smoke-tests-on-macos.yaml

The `--preinstall` option for brew update doesn't exist and [passing non-existent options to the brew update command in newer homebrew versions causes an error with exit code 1.](https://github.com/Homebrew/brew/pull/19083)
This can be observed in [failing Smoke Tests workflow runs](https://github.com/hiero-ledger/hiero-local-node/actions/runs/13367865032/job/37329606656) from the last month or so.

ci: remove unrecognized brew update option in Smoke Tests

---

compose-network/network-node/data/config/api-permission.properties
compose-network/network-node/data/config/application.properties
compose-network/network-node/data/config/bootstrap.properties

Due to newly introduced gradle standards in the hiero org, the properties files now have to pass gradle spotlessCheck.
I am modifying these files so repositories that clone this repo and also run spotlessCheck as part of the same workflow job don't experience issues during the workflow run.
Related to: [#152](https://github.com/hiero-ledger/hiero-gradle-conventions/issues/152)
**Checklist**

chore: modify properties files in accordance with gradle spotless rules

---

package-lock.json
package.json

Bump hiero-local-node version to 2.36.0
Fixes #
**Checklist**

chore: Bump local-node to 2.36.0

---

.env
config.yaml
docker-compose.yml
src/configuration/local.json

Bump docker image versions for latest product versions
- CN to 0.62.2
- BN to 0.9.0
- MN to 0.129.0
- Relay to 0.67.0
Fixes #1062 
**Checklist**

chore: Bump docker images to latest netowkr versions around 0.62.2

---

package-lock.json
package.json

This PR aims to:
- Bump the local-node version to 2.36.3
- Lock SDK version to the latest stable one.
Fixes #1070
Fixes #1069
**Checklist**

chore: bump local-node version and lock sdk

---

src/services/CLIService.ts

This PR flips the enable block node feature flag to false, until the node matures enough to be enabled.
Fixes #
**Checklist**

chore: revert `block-node` enabled by default

---

src/controller/StateController.ts
src/state/InitState.ts
test/unit/states/InitState.spec.ts

Changes:
- Added a new ASCII art logo display for Hiero Local-Node
- Implemented a structured version and configuration information display
- Reduced log verbosity by changing several `info` logs to `trace` level in certain places
New Features:
1. **Logo Display**
- Added ASCII art logo for "Hiero" and "Local-Node"
- Centered and properly formatted display
2. **Version Information**
- Added Local-Node version from package.json
- Added Hiero Nodes version section showing:
- Consensus Node Version
- Mirror Node Version
- Relay Version
- Block Node Version
3. **Configuration Status**
- Added a new section showing:
- Node Configuration (Single/Multi)
- Block Node status
- Host address
- Verbose Level (using VerboseLevel enum)
Technical Changes:
- Added new …

feat: improve devex in cli

---

.env
config.yaml
src/configuration/local.json

Update node versions for 0.64.0 milestone
- Bump CN to 0.64.0
- Bump MN to 0.133.1
- Bump relay to 0.69.3
Fixes #
**Checklist**

chore: Update node versions for 0.64.0 milestone
